### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by servantthought** [iZeaoGamer/EssentialsPE#13]
I see this is a massive plugin compared to its out dated competitor  EssentialsTP... does yours have /wild it would be useful I'm planning on using EssentialsPE alongside your  FactionsPro plugin...

**Comment by TheFixerDevelopment** [comment]
We'll see if we can add it. Thanks.

**Comment by ZPlayzMCPE** [comment]
Closed for now.

**Comment by artulloss** [comment]
@ZPlayzMCPE please make it configurable so you can disable if needed, /wild in essentials tp is broken I believe.
