### ISSUE TITLE
Since Pocketmine update 683..

### ISSUE THREAD

**Issue by ghost** [iZeaoGamer/EssentialsPE#3]
{0%} joined the game (tested, happens only with this plugin)

**Comment by iZeaoGamer** [comment]
Is this issue fixed for you? As you just closed the issue. I had this issue, and are working on fixing it. I'll reopen it and add it as "Bug" untill I fix it.

**Comment by ghost** [comment]
Yeah I found a fix recently and fixed it myself but okay thanks anyway

**Comment by iZeaoGamer** [comment]
Oh, it's okay. Closing issue.
