### ISSUE TITLE
Warps Reset on restart

### ISSUE THREAD

**Issue by OfficialLilKev** [iZeaoGamer/EssentialsPE#4]
Could you please have this fixed

**Comment by iZeaoGamer** [comment]
This should now be fixed. Please test it and let me know if it's fixed or not. Thank you. - Just update to the latest Commit build.

**Comment by iZeaoGamer** [comment]
Okay, I've checked your solution. As far as I'm concerned, it is now fixed. I tried this with build 699 of Pocketmine with no issues. This should also be fixed with newer versions of Pocketmine. If you have any more issues or concerns, feel free to open a new issue. Closing issue as it's Fixed.
