### ISSUE TITLE
Crash when i used /setwarp or /sethome

### ISSUE THREAD

**Issue by orangetictac** [iZeaoGamer/EssentialsPE#6]
Fix please: [error](https://pastebin.com/7FhCs2cS)

**Comment by iZeaoGamer** [comment]
Okay, please update to the latest Poggit build. The errors you're experiencing should be fixed. Please reply back on if it's fixed or not. If it is, I will close the issue. For now, tagging this issue as "NEEDS TESTING".

**Comment by iZeaoGamer** [comment]
Okay, I have confirmed this has been fixed. I've tested it myself with no issues whatsoever. This should also work with newer versions of Pocketmine as well. Closing issue as it is now fixed. If you have more issues, please open a new issue. Thank you.
