### ISSUE TITLE
Fix this issue

### ISSUE THREAD

**Issue by orangetictac** [iZeaoGamer/EssentialsPE#7]
Hello, i have this error when server is stared. fix please: [error](https://pastebin.com/kjVBnN1j)

**Comment by marc0525** [comment]
Hello, i set up the perms for /repair but when players do /repair it says "An unknown error has occured"

**Comment by iZeaoGamer** [comment]
What Pocketmine build are you on?

**Comment by ZPlayzMCPE** [comment]
Can someone test this bug, and let me know if it’s a confirmed bug or not, as I have no issues with this.
